export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const UPDATE_COLUMN = "UPDATE_COLUMN";
export const ADD_REQUEST = "ADD_REQUEST";
export const REMOVE_REQUEST = "REMOVE_REQUEST";

export const ENTITY_USER_LOADED='ENTITY_USER_LOADED';
export const ENTITY_REFERENCES_LOADED='ENTITY_REFERENCES_LOADED';
export const ENTITY_TICKETS_LOADED='ENTITY_TICKETS_LOADED';
export const ENTITY_REQUEST='ENTITY_REQUEST';





export const REQUESTED_DOG='REQUESTED_DOG';
export const REQUESTED_DOG_SUCCEEDED='REQUESTED_DOG_SUCCEEDED';
export const REQUESTED_DOG_FAILED='REQUESTED_DOG_FAILED';
export const FETCHED_DOG='FETCHED_DOG';


export const GET_TICKET_ID = `GET_TICKET_ID`;
export const LOAD_COMMENTS = `LOAD_COMMENTS`;
export const LOAD_COMMENTS_ID = `LOAD_COMMENTS_ID`;
export const POST_COMMENT = `POST_COMMENT`;










export const SET_CASCADER_OPTION = `Comments/SET_CASCADER_OPTION`
export const DELETE_COMMENT = `Comments/DELETE_COMMENT`
export const EDIT_COMMENT = `Comments/EDIT_COMMENT`
export const LOAD_CHILDREN_DEVICES = `Comments/LOAD_CHILDREN_DEVICES`

export const LOAD_DEFAULT_OPTIONS = `Comments/LOAD_DEFAULT_OPTIONS`
export const LOAD_PARENT_DEVICES = `Comments/LOAD_PARENT_DEVICES`
export const MERGE_PARENT_DEVICES = `Comments/MERGE_PARENT_DEVICES`

export const PREPARE_OPTIONS = `Comments/PREPARE_OPTIONS`
export const SET_TYPE = `Comments/SET_TYPE`
