export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const UPDATE_COLUMN = "UPDATE_COLUMN";


export const ENTITY_USER_LOADED='ENTITY_USER_LOADED';
export const ENTITY_REFERENCES_LOADED='ENTITY_REFERENCES_LOADED';
export const ENTITY_REQUEST='ENTITY_REQUEST';

